// Generated by tools/generate-i18n.py; edit i18n/messages, not this file.
package dev.ghost.nearbyim.i18n;

import java.util.*;

/** Supported display languages, independent of either platform's widgets. */
public final class LanguageRegistry {
    public static final String SYSTEM = "system";
    public static final String VERSION = "0.3.0";
    public static final String FALLBACK = "en";
    public static final class Language {
        public final String tag, nativeName;
        public final boolean rtl;
        private Language(String tag, String nativeName, boolean rtl) {
            this.tag = tag; this.nativeName = nativeName; this.rtl = rtl;
        }
        @Override public String toString() { return nativeName; }
    }
    private static final List<Language> LANGUAGES = Collections.unmodifiableList(Arrays.asList(
            new Language("zh-Hans", "简体中文", false),
            new Language("en", "English", false)));
    private static final Map<String, String> ALIASES;
    static {
        Map<String, String> aliases = new HashMap<>();
        aliases.put("zh-hans", "zh-Hans");
        aliases.put("zh", "zh-Hans");
        aliases.put("zh-cn", "zh-Hans");
        aliases.put("zh-sg", "zh-Hans");
        aliases.put("en", "en");
        aliases.put("en-latn", "en");
        ALIASES = Collections.unmodifiableMap(aliases);
    }
    private LanguageRegistry() {}
    public static List<Language> languages() { return LANGUAGES; }
    private static String supported(String value) {
        if (value == null || value.trim().isEmpty()) return null;
        String tag = value.trim().replace('_', '-');
        String alias = ALIASES.get(tag.toLowerCase(Locale.ROOT));
        if (alias != null) return alias;
        Locale requested = Locale.forLanguageTag(tag);
        // Locale extensions customize formatting, not the translated language.
        alias = ALIASES.get(requested.stripExtensions().toLanguageTag().toLowerCase(Locale.ROOT));
        if (alias != null) return alias;
        if (!requested.getScript().isEmpty()) {
            String scriptTag = new Locale.Builder().setLanguage(requested.getLanguage()).setScript(requested.getScript()).build().toLanguageTag();
            alias = ALIASES.get(scriptTag.toLowerCase(Locale.ROOT));
            if (alias != null) return alias;
        }
        for (Language language : LANGUAGES) {
            Locale available = Locale.forLanguageTag(language.tag);
            if (available.getLanguage().equals(requested.getLanguage()) &&
                    available.getScript().equals(requested.getScript())) return language.tag;
        }
        return null;
    }
    public static String normalizeSelection(String selection) {
        String tag = supported(selection);
        return tag == null ? SYSTEM : tag;
    }
    public static Language resolve(String selection, Locale system) {
        String normalized = normalizeSelection(selection);
        String tag = normalized.equals(SYSTEM) ? supported((system == null ? Locale.getDefault() : system).toLanguageTag()) : normalized;
        if (tag == null) tag = FALLBACK;
        for (Language language : LANGUAGES) if (language.tag.equals(tag)) return language;
        throw new IllegalStateException("Fallback language missing from registry");
    }
    public static Locale locale(String selection, Locale system) {
        Locale actualSystem = system == null ? Locale.getDefault() : system;
        Language resolved = resolve(selection, actualSystem);
        if (normalizeSelection(selection).equals(SYSTEM) && supported(actualSystem.toLanguageTag()) != null) return actualSystem;
        return Locale.forLanguageTag(resolved.tag);
    }
}
