#!/usr/bin/env python3
"""Generate both platforms' resources from the reviewed UTF-8 ICU catalogs.

No dependency is required. ICU itself validates every generated pattern in the
desktop test suite; this generator checks the portable subset and cross-language
argument contract before any Android resource compilation.
"""
import argparse
import json
from pathlib import Path
import re
import sys
from xml.sax.saxutils import escape

HEADER = "Generated by tools/generate-i18n.py; edit i18n/messages, not this file."
BASE = Path(__file__).resolve().parents[1]
JAVA_DIR = "app/src/main/java/dev/ghost/nearbyim/i18n"
DESKTOP_DIR = "desktop/src/main/resources/dev/ghost/wozai"


def read_json_text(text):
    def unique(items):
        result = {}
        for key, value in items:
            if key in result:
                raise ValueError(f"Duplicate JSON key: {key}")
            result[key] = value
        return result
    return json.loads(text, object_pairs_hook=unique)


def read_json(path):
    return read_json_text(path.read_text(encoding="utf-8"))


def parse_parameters(pattern):
    """Validate numeric ICU arguments, nested selectors and optional apostrophes."""
    arguments = {}
    size = len(pattern)

    def quoted(pos):
        if pos + 1 < size and pattern[pos + 1] == "'":
            return pos + 2
        if pos + 1 == size or pattern[pos + 1] not in "{}#":
            return pos + 1  # ordinary apostrophe, e.g. I'm
        pos += 1
        while pos < size:
            if pattern[pos] == "'":
                if pos + 1 < size and pattern[pos + 1] == "'":
                    pos += 2
                else:
                    return pos + 1
            else:
                pos += 1
        raise ValueError("Unclosed ICU quoted literal")

    def spaces(pos):
        while pos < size and pattern[pos].isspace():
            pos += 1
        return pos

    def message(pos, nested=False):
        while pos < size:
            if pattern[pos] == "'":
                pos = quoted(pos)
            elif pattern[pos] == "{":
                pos = argument(pos + 1)
            elif pattern[pos] == "}":
                if nested:
                    return pos + 1
                raise ValueError("Unexpected ICU closing brace")
            else:
                pos += 1
        if nested:
            raise ValueError("Unclosed ICU argument")
        return pos

    def argument(pos):
        pos = spaces(pos)
        found = re.match(r"\d+", pattern[pos:])
        if not found:
            raise ValueError("ICU arguments must use numeric indices")
        index = int(found.group())
        pos = spaces(pos + len(found.group()))
        kind = "text"
        if pos < size and pattern[pos] == ",":
            pos = spaces(pos + 1)
            found = re.match(r"[a-zA-Z]+", pattern[pos:])
            if not found:
                raise ValueError("Missing ICU argument type")
            kind = found.group().lower()
            if kind not in {"number", "date", "time", "plural", "selectordinal", "select"}:
                raise ValueError(f"Unsupported ICU argument type: {kind}")
            pos = spaces(pos + len(found.group()))
        if index in arguments and arguments[index] != kind:
            raise ValueError(f"Conflicting ICU types for argument {index}")
        arguments[index] = kind
        if pos < size and pattern[pos] == "}" and kind not in {"plural", "selectordinal", "select"}:
            return pos + 1
        if pos >= size or pattern[pos] != "," or kind == "text":
            raise ValueError("Invalid ICU argument")
        pos = spaces(pos + 1)
        if kind not in {"plural", "selectordinal", "select"}:
            while pos < size and pattern[pos] != "}":
                if pattern[pos] == "{":
                    raise ValueError("Nested brace in ICU format style")
                pos = quoted(pos) if pattern[pos] == "'" else pos + 1
            if pos == size:
                raise ValueError("Unclosed ICU format style")
            return pos + 1
        selectors = set()
        if kind != "select" and pattern.startswith("offset:", pos):
            found = re.match(r"offset:\s*\d+", pattern[pos:])
            if not found:
                raise ValueError("Invalid ICU plural offset")
            pos = spaces(pos + len(found.group()))
        while pos < size and pattern[pos] != "}":
            found = re.match(r"(?:=[-+]?\d+(?:\.\d+)?|[a-zA-Z][\w-]*)", pattern[pos:])
            if not found:
                raise ValueError("Invalid ICU selector")
            selector = found.group()
            if selector in selectors:
                raise ValueError(f"Duplicate ICU selector: {selector}")
            selectors.add(selector)
            pos = spaces(pos + len(selector))
            if pos >= size or pattern[pos] != "{":
                raise ValueError("ICU selector needs a message")
            pos = spaces(message(pos + 1, nested=True))
        if pos == size or "other" not in selectors:
            raise ValueError("ICU selector requires other and a closing brace")
        return pos + 1

    message(0)
    return arguments


def resource_name(key):
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2",
                  re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", key)).lower()


def validate(config, messages):
    if not re.fullmatch(r"\d+\.\d+\.\d+", config.get("appVersion", "")):
        raise ValueError("appVersion must be a three-part release version")
    languages = config["languages"]
    tags = [item["tag"] for item in languages]
    if len(set(tags)) != len(tags) or not languages:
        raise ValueError("Duplicate or empty language registry")
    if set(tags) != set(messages) or config["sourceLanguage"] not in tags or config["fallbackLanguage"] not in tags:
        raise ValueError("Catalog language files must exactly match the registry")
    aliases = {}
    qualifiers = set()
    for item in languages:
        if not re.fullmatch(r"[a-z]{2,3}(?:-[A-Za-z0-9]{2,8})*", item["tag"]):
            raise ValueError(f"Invalid BCP-47 language tag: {item['tag']}")
        parts = item["tag"].split("-")
        canonical = "-".join([parts[0]] + [part.title() if len(part) == 4 and part.isalpha()
            else part.upper() if len(part) == 2 or (len(part) == 3 and part.isdigit()) else part.lower() for part in parts[1:]])
        if item["tag"] != canonical:
            raise ValueError(f"Language tag must use canonical BCP-47 casing: {canonical}")
        if not item["nativeName"] or not isinstance(item["rtl"], bool):
            raise ValueError("Each language needs a nativeName and boolean rtl")
        qualifier = item["androidQualifier"]
        if not re.fullmatch(r"[a-z]{2,3}|b\+[A-Za-z0-9+]+", qualifier) or qualifier in qualifiers:
            raise ValueError("Invalid or duplicate Android language qualifier")
        qualifier_tag = (qualifier[2:] if qualifier.startswith("b+") else qualifier).replace("+", "-")
        if qualifier_tag != item["tag"]:
            raise ValueError(f"Android language qualifier must match tag: {item['tag']}")
        qualifiers.add(qualifier)
        for alias in [item["tag"]] + item["aliases"]:
            normalized = alias.replace("_", "-").lower()
            if normalized in aliases and aliases[normalized] != item["tag"]:
                raise ValueError(f"Ambiguous language alias: {alias}")
            aliases[normalized] = item["tag"]
    source = messages[config["sourceLanguage"]]
    if not source:
        raise ValueError("Translation catalog is empty")
    resource_names = {}
    for key in source:
        if not re.fullmatch(r"[a-z][A-Za-z0-9]*", key):
            raise ValueError(f"Message keys must be lowerCamelCase: {key}")
        name = resource_name(key)
        if name in resource_names:
            raise ValueError(f"Android resource name collision: {key}, {resource_names[name]}")
        resource_names[name] = key
    contracts = {}
    for tag, catalog in messages.items():
        if set(catalog) != set(source):
            raise ValueError(f"{tag} keys differ: missing={sorted(set(source)-set(catalog))}, extra={sorted(set(catalog)-set(source))}")
        contracts[tag] = {}
        for key, value in catalog.items():
            if not isinstance(value, str) or not value:
                raise ValueError(f"{tag}:{key} must be a nonempty string")
            try:
                contracts[tag][key] = parse_parameters(value)
            except ValueError as error:
                raise ValueError(f"{tag}:{key}: {error}") from error
    for tag in tags:
        for key in source:
            if contracts[tag][key] != contracts[config["sourceLanguage"]][key]:
                raise ValueError(f"{tag}:{key} parameters differ from source language")


def java_string(value):
    return json.dumps(value, ensure_ascii=False)


def registry(config):
    entries = ",\n            ".join("new Language(%s, %s, %s)" % (
        java_string(item["tag"]), java_string(item["nativeName"]), str(item["rtl"]).lower())
        for item in config["languages"])
    aliases = "\n        ".join("aliases.put(%s, %s);" % (java_string(alias.lower().replace("_", "-")), java_string(item["tag"]))
        for item in config["languages"] for alias in [item["tag"]] + item["aliases"])
    return f'''// {HEADER}
package dev.ghost.nearbyim.i18n;

import java.util.*;

/** Supported display languages, independent of either platform's widgets. */
public final class LanguageRegistry {{
    public static final String SYSTEM = "system";
    public static final String VERSION = {java_string(config['appVersion'])};
    public static final String FALLBACK = {java_string(config['fallbackLanguage'])};
    public static final class Language {{
        public final String tag, nativeName;
        public final boolean rtl;
        private Language(String tag, String nativeName, boolean rtl) {{
            this.tag = tag; this.nativeName = nativeName; this.rtl = rtl;
        }}
        @Override public String toString() {{ return nativeName; }}
    }}
    private static final List<Language> LANGUAGES = Collections.unmodifiableList(Arrays.asList(
            {entries}));
    private static final Map<String, String> ALIASES;
    static {{
        Map<String, String> aliases = new HashMap<>();
        {aliases}
        ALIASES = Collections.unmodifiableMap(aliases);
    }}
    private LanguageRegistry() {{}}
    public static List<Language> languages() {{ return LANGUAGES; }}
    private static String supported(String value) {{
        if (value == null || value.trim().isEmpty()) return null;
        String tag = value.trim().replace('_', '-');
        String alias = ALIASES.get(tag.toLowerCase(Locale.ROOT));
        if (alias != null) return alias;
        Locale requested = Locale.forLanguageTag(tag);
        // Locale extensions customize formatting, not the translated language.
        alias = ALIASES.get(requested.stripExtensions().toLanguageTag().toLowerCase(Locale.ROOT));
        if (alias != null) return alias;
        if (!requested.getScript().isEmpty()) {{
            String scriptTag = new Locale.Builder().setLanguage(requested.getLanguage()).setScript(requested.getScript()).build().toLanguageTag();
            alias = ALIASES.get(scriptTag.toLowerCase(Locale.ROOT));
            if (alias != null) return alias;
        }}
        for (Language language : LANGUAGES) {{
            Locale available = Locale.forLanguageTag(language.tag);
            if (available.getLanguage().equals(requested.getLanguage()) &&
                    available.getScript().equals(requested.getScript())) return language.tag;
        }}
        return null;
    }}
    public static String normalizeSelection(String selection) {{
        String tag = supported(selection);
        return tag == null ? SYSTEM : tag;
    }}
    public static Language resolve(String selection, Locale system) {{
        String normalized = normalizeSelection(selection);
        String tag = normalized.equals(SYSTEM) ? supported((system == null ? Locale.getDefault() : system).toLanguageTag()) : normalized;
        if (tag == null) tag = FALLBACK;
        for (Language language : LANGUAGES) if (language.tag.equals(tag)) return language;
        throw new IllegalStateException("Fallback language missing from registry");
    }}
    public static Locale locale(String selection, Locale system) {{
        Locale actualSystem = system == null ? Locale.getDefault() : system;
        Language resolved = resolve(selection, actualSystem);
        if (normalizeSelection(selection).equals(SYSTEM) && supported(actualSystem.toLanguageTag()) != null) return actualSystem;
        return Locale.forLanguageTag(resolved.tag);
    }}
}}
'''


def android_string(value):
    # Android strips the outer quotes; they preserve leading/trailing whitespace
    # and protect @/? from resource-reference interpretation. ICU sees the original.
    encoded = value.replace("\\", "\\\\").replace("'", "\\'").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return escape('"' + encoded + '"')


def properties_string(value):
    encoded = value.replace("\\", "\\\\").replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    leading = len(encoded) - len(encoded.lstrip(" "))
    return "\\ " * leading + encoded[leading:]


def outputs(config, messages):
    validate(config, messages)
    result = {f"{JAVA_DIR}/LanguageRegistry.java": registry(config)}
    keys = sorted(messages[config["sourceLanguage"]])
    def xml(catalog):
        body = "\n".join(f'    <string name="{resource_name(key)}" formatted="false">{android_string(catalog[key])}</string>' for key in keys)
        return f'<?xml version="1.0" encoding="utf-8"?>\n<!-- {HEADER} -->\n<resources>\n{body}\n</resources>\n'
    def props(catalog):
        return "# " + HEADER + "\n" + "\n".join(key + "=" + properties_string(catalog[key]) for key in keys) + "\n"
    fallback = messages[config["fallbackLanguage"]]
    result["app/src/main/res/values/strings.xml"] = xml(fallback)
    result[f"{DESKTOP_DIR}/Strings.properties"] = props(fallback)
    for language in config["languages"]:
        tag = language["tag"]
        result[f"app/src/main/res/values-{language['androidQualifier']}/strings.xml"] = xml(messages[tag])
        result[f"{DESKTOP_DIR}/Strings_{tag.replace('-', '_')}.properties"] = props(messages[tag])
    locales = "\n".join(f'    <locale android:name="{language["tag"]}" />' for language in config["languages"])
    result["app/src/main/res/xml/locales_config.xml"] = f'<?xml version="1.0" encoding="utf-8"?>\n<!-- {HEADER} -->\n<locale-config xmlns:android="http://schemas.android.com/apk/res/android">\n{locales}\n</locale-config>\n'
    mapping = "\n".join(f'            case "{key}": return R.string.{resource_name(key)};' for key in keys)
    result[f"{JAVA_DIR}/I18nResources.java"] = f'''// {HEADER}
package dev.ghost.nearbyim.i18n;

import dev.ghost.nearbyim.R;

/** Direct resource references remain visible to AAPT, shrinkers and source checks. */
public final class I18nResources {{
    private I18nResources() {{}}
    public static int id(String key) {{
        if (key == null) return 0;
        switch (key) {{
{mapping}
            default: return 0;
        }}
    }}
}}
'''
    return result


def run(root, check=False):
    config = read_json(root / "i18n/config.json")
    messages = {path.stem: read_json(path) for path in sorted((root / "i18n/messages").glob("*.json"))}
    generated = outputs(config, messages)
    candidates = list((root / "app/src/main/res").glob("values*/strings.xml")) + list((root / DESKTOP_DIR).glob("Strings*.properties"))
    orphaned = [path for path in candidates if HEADER in path.read_text(encoding="utf-8") and path.relative_to(root).as_posix() not in generated]
    if orphaned and check:
        raise ValueError("orphan generated resources: " + ", ".join(str(path.relative_to(root)) for path in orphaned))
    for path in orphaned:
        path.unlink()
    changed = []
    for relative, content in generated.items():
        path = root / relative
        if not path.exists() or path.read_bytes() != content.encode("utf-8"):
            changed.append(relative)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(content.encode("utf-8"))
    if check and changed:
        raise ValueError("Outdated generated files; run python3 tools/generate-i18n.py: " + ", ".join(changed))
    return len(messages), len(next(iter(messages.values()))), changed


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if checked-in output differs")
    parser.add_argument("--root", type=Path, default=BASE, help=argparse.SUPPRESS)
    args = parser.parse_args()
    try:
        languages, keys, changed = run(args.root, check=args.check)
        print(f"i18n: {languages} complete languages, {keys} keys, {len(changed)} generated files updated")
    except (ValueError, KeyError, json.JSONDecodeError) as error:
        print(f"i18n: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
